export const DOCUMENTATION_REQUEST = "API/DOCUMENTATION/REQUEST";
export const DOCUMENTATION_SUCCESS = "API/DOCUMENTATION/RECEIVE/SUCCESS";
export const DOCUMENTATION_ERROR   = "API/DOCUMENTATION/RECEIVE/ERROR";